base_url = "https://bencollins.ovh/"
title = "Ben Collins"
description = "Developer profile website for Ben Collins"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false

[markdown]
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false
github_alerts = true

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
sections = [
  { name = "experience", path = "/experience", is_external = false },
  { name = "education", path = "/education", is_external = false },
  { name = "personal projects", path = "/personal-projects", is_external = false },
]

back_link_text = "Back"
force_theme = false

footer_copyright = "© 2025 Benjamin Collins"
footer_credits = true

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"
