[[collection]]
type = "card"
title = "BSc (Hons), Computer Science, First Class"
subtitle = "Royal Holloway, University of London"
date = "Sep 2021 - Jun 2024"
content = "Final year project grade (88%), Overall grade (86%)"
