[[collection]]
type = "card"
title = "BSc (Hons), Computer Science, First Class"
subtitle = "Royal Holloway University of London"
date = "Sep 2021 - Jun 2024"
content = "Relevant modules: Object Oriented Programming I, Programming Laboratory, Machine Fundamentals, Software Development, Software Design, Mathematical Structures, Internet Services"
