[[collection]]
type = "card"
title = "Go Generics Survey"
link = "https://github.com/julien-lange/go-generics-survey"
content = """
Generics were introduced in Go 1.18. TODO
"""
tags = ["golang", "python"]

[[collection]]
type = "card"
title = "Open Bot Brain"
date = "Jul 2023 - Sep 2023"
link = ""
content = """
- Built and tested firmware for a custom board with an Arm microcontroller in Rust.
- Wrote drivers for various different sensors and controllers including a combined gyroscope, accelerometer and magnetometer.
- Worked on a prototype for a protocol description language to generate well typed APIs for protocols to facilitate communication between the microcontroller and a Raspberry Pi over a UART bus.
"""
tags = ["embedded software", "rust", "session types"]

[[collection]]
type = "card"
title = "Certifiably Correct Regular Expressions"
date = "Jul 2022 - Sep 2022"
content = """
- Successfully completed an undergraduate research project on Certifiably Correct Regular Expressions.
- Used the Verified Software Toolchain and Rocq to prove that a regular expression implementation in C was correct.
- Produced a report detailing my project and the experience Iâ€™ve gained using the VST.
"""
tags = ["proof theory", "c", "rocq"]
